stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data1/SAHeart.csv
    outs:
    - data1/raw/SAHeart.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data1/raw/SAHeart.csv
    outs:
    - data1/processed/train.csv
    - data1/processed/test.csv 

  train_and_evaluate:
    cmd: [python src/train_and_evaluate.py --config=params.yaml, dvc plots show]
    
    deps:
    - data1/processed/train.csv
    - data1/processed/test.csv 
    - src/train_and_evaluate.py
    
    metrics:
    - report/scores.json:
        cache: false

    plots:
      
    - report/prc.json:
        cache: false
        x: recall
        y: precision
    - report/roc.json:
        cache: false
        x: fpr
        y: tpr
    - cm.csv:
        cache: false
        

    outs:
    - saved_models/model.joblib

#